import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
const config = JSON.parse(await readFile('site.config.json', 'utf8'));
const siteUrl = (process.env.SITE_URL ?? config.siteUrl ?? '').replace(/\/$/, '');
const absoluteUrl = (path) => siteUrl ? `${siteUrl}${path}` : '';
const canonical = (path) => { const url = absoluteUrl(path); return url ? `<link rel=\"canonical\" href=\"${url}\">` : ''; };
const ogUrl = (path) => { const url = absoluteUrl(path); return url ? `<meta property=\"og:url\" content=\"${url}\">` : ''; };
const company='Sinar Jaya SAE';
const wa='https://wa.me/6281239998129';
const products=[
 ['sjs-multy-blanding','SJS Multy Blanding','Portofolio pupuk Sinar Jaya SAE untuk kebutuhan nutrisi pertanian.'],
 ['sp-36','SP-36','Produk pupuk dalam portofolio Sinar Jaya SAE.'],
 ['sjs-agrophos','SJS Agrophos','Produk pupuk fosfat dalam portofolio Sinar Jaya SAE.'],
 ['sawit-mas-13-6-27-te','Sawit Mas 13-6-27+TE','Produk pupuk sawit dalam portofolio Sinar Jaya SAE.'],
 ['golden-premium','Golden Premium','Produk pupuk dalam portofolio Sinar Jaya SAE.']
];
const nav=[['/','Beranda'],['/tentang-kami/','Tentang Kami'],['/produk/','Produk'],['/solusi/','Solusi'],['/distribusi/','Distribusi'],['/artikel/','Artikel'],['/kontak/','Kontak']];
function header(active='') {return `<a class="skip" href="#konten">Lewati navigasi</a><header class="site-header"><nav class="nav container" aria-label="Navigasi utama"><a class="brand" href="/"><span class="brand-name">SINAR JAYA SAE<small>SOLUSI NUTRISI PERTANIAN</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="menu">Menu</button><div class="nav-links" id="menu">${nav.map(([u,n])=>`<a href="${u}" ${active===u?'aria-current="page"':''}>${n}</a>`).join('')}<a class="button" href="${wa}" target="_blank" rel="noopener">WhatsApp</a></div></nav></header>`}
function footer(){return `<a class="wa-float" href="${wa}" target="_blank" rel="noopener" aria-label="Hubungi Sinar Jaya SAE melalui WhatsApp">WA</a><footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="/"><span class="brand-name">SINAR JAYA SAE<small>SOLUSI NUTRISI PERTANIAN</small></span></a><p>Industri pupuk fosfat alam dan mineral pertanian dari Gresik, Jawa Timur.</p></div><div><h3>Navigasi</h3><p><a href="/tentang-kami/">Tentang Kami</a><br><a href="/produk/">Produk</a><br><a href="/solusi/">Solusi Pertanian</a><br><a href="/artikel/">Artikel & Informasi</a></p></div><div><h3>Kontak</h3><p><a href="${wa}">0812-3999-8129</a><br><a href="mailto:cvsinarjayasae@gmail.com">cvsinarjayasae@gmail.com</a><br>Gresik, Jawa Timur, Indonesia</p></div></div><div class="container copyright">© ${new Date().getFullYear()} Sinar Jaya SAE. Seluruh hak cipta dilindungi.</div></footer><script src="/assets/site.js" defer></script>`}
function schema(name=company,description='Website resmi Sinar Jaya SAE.',path='/') { const org={'@type':'Organization','name':company,'email':'cvsinarjayasae@gmail.com','telephone':'+6281239998129','address':{'@type':'PostalAddress','addressLocality':'Gresik','addressRegion':'Jawa Timur','addressCountry':'ID'},'areaServed':'Indonesia'}; const webpage={'@type':'WebPage','name':name,'description':description}; const url=absoluteUrl(path); if(url){org.url=siteUrl;webpage.url=url;} return `<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':[org,webpage]})}</script>`}
function page({title,desc,path,active,body}){return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}">${canonical(path)}<meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}">${ogUrl(path)}<meta property="og:locale" content="id_ID"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${desc}"><link rel="stylesheet" href="/assets/site.css">${schema(title,desc,path)}</head><body>${header(active)}<main id="konten">${body}</main>${footer()}</body></html>`}
function hero(title,text,crumb=''){return `<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="/">Beranda</a>${crumb?' / '+crumb:''}</div><h1>${title}</h1><p>${text}</p></div></section>`}
const productsCards=products.map(([slug,name,desc])=>`<article class="product"><div class="product-image"><span>Placeholder foto kemasan asli</span></div><div class="product-body"><h3>${name}</h3><p>${desc}</p><a class="text-link" href="/produk/${slug}/">Lihat detail produk →</a></div></article>`).join('');
for (const route of ['tentang-kami','solusi','distribusi','artikel','kontak']) { await rm(`public/${route}.html`, { force: true }); await mkdir(`public/${route}`, { recursive: true }); }
await mkdir('public/produk',{recursive:true});
await writeFile('public/index.html',page({title:'Sinar Jaya SAE | Solusi Nutrisi untuk Pertanian Indonesia',desc:'Sinar Jaya SAE adalah industri pupuk fosfat alam dan mineral pertanian dari Gresik, Jawa Timur, dengan distribusi ke seluruh Indonesia.',path:'/',active:'/',body:`<section class="hero"><div class="container hero-grid"><div><p class="eyebrow" style="color:#c8df8c">Gresik, Jawa Timur</p><h1>Solusi Nutrisi untuk Pertanian Indonesia</h1><p>Sinar Jaya SAE menghadirkan portofolio pupuk fosfat alam dan mineral pertanian untuk mendukung kebutuhan pertanian di Indonesia.</p><a class="button" href="/produk/">Jelajahi Produk</a></div><aside class="hero-card"><strong>Distribusi nasional</strong><span>Melayani kebutuhan pelanggan di seluruh Indonesia.</span><br><br><strong>Pengalaman ekspor</strong><span>Pernah menyalurkan produk ke Timor-Leste.</span></aside></div></section><section><div class="container intro-grid"><div class="section-heading"><p class="eyebrow">Profil perusahaan</p><h2>Fokus pada pupuk fosfat alam dan mineral pertanian.</h2><p>Berlokasi di Gresik, Jawa Timur, Sinar Jaya SAE membangun layanan untuk kebutuhan pupuk pertanian dan distribusi di berbagai wilayah Indonesia.</p><p><a class="text-link" href="/tentang-kami/">Mengenal Sinar Jaya SAE →</a></p></div><div class="panel"><h2>Jangkauan & layanan</h2><ul class="facts"><li><b>Lokasi</b>Gresik, Jawa Timur, Indonesia</li><li><b>Distribusi</b>Seluruh Indonesia</li><li><b>Ekspor</b>Berpengalaman ekspor ke Timor-Leste</li></ul></div></div></section><section class="band"><div class="container"><div class="section-heading"><p class="eyebrow" style="color:#c8df8c">Portofolio</p><h2>Produk untuk berbagai kebutuhan pertanian.</h2><p>Temukan informasi singkat setiap produk dan hubungi tim kami untuk pembahasan kebutuhan Anda.</p></div><div class="product-grid">${productsCards}</div></div></section><section><div class="container"><div class="section-heading"><p class="eyebrow">Solusi & aplikasi</p><h2>Mendampingi kebutuhan nutrisi pertanian.</h2></div><div class="cards"><article class="card"><h3>Pupuk fosfat alam</h3><p>Informasi produk untuk kebutuhan pertanian berbasis fosfat alam.</p></article><article class="card"><h3>Nutrisi tanaman</h3><p>Struktur informasi untuk membantu percakapan awal mengenai kebutuhan pemupukan.</p></article><article class="card"><h3>Pupuk sawit</h3><p>Portofolio produk untuk kebutuhan pemupukan sawit tersedia untuk dipelajari.</p></article></div></div></section><section><div class="container cta"><div><p class="eyebrow" style="color:#dff0b8">Hubungi kami</p><h2>Diskusikan kebutuhan produk pertanian Anda.</h2></div><a class="button outline" href="${wa}" target="_blank" rel="noopener">Chat via WhatsApp</a></div></section>`}));
await writeFile('public/tentang-kami/index.html',page({title:'Tentang Kami | Sinar Jaya SAE',desc:'Profil Sinar Jaya SAE, industri pupuk fosfat alam dan mineral pertanian di Gresik, Jawa Timur.',path:'/tentang-kami/',active:'/tentang-kami/',body:`${hero('Tentang Sinar Jaya SAE','Industri pupuk fosfat alam dan mineral pertanian yang berlokasi di Gresik, Jawa Timur.','Tentang Kami')}<section><div class="container prose"><h2>Profil perusahaan</h2><p>Sinar Jaya SAE berfokus pada industri pupuk fosfat alam dan mineral pertanian. Kami melayani distribusi produk ke seluruh Indonesia dan memiliki pengalaman ekspor ke Timor-Leste.</p><h2>Visi</h2><p>Menjadi mitra yang dapat diandalkan untuk kebutuhan nutrisi pertanian melalui produk dan layanan yang relevan bagi pelanggan.</p><h2>Misi</h2><ul><li>Menyediakan portofolio pupuk pertanian yang dapat dipelajari dengan informasi yang jelas.</li><li>Melayani kebutuhan distribusi pelanggan di berbagai wilayah Indonesia.</li><li>Membangun komunikasi yang responsif untuk mendukung kebutuhan pelanggan.</li></ul></div></section>`}));
await writeFile('public/produk/index.html',page({title:'Produk Pupuk | Sinar Jaya SAE',desc:'Portofolio produk pupuk Sinar Jaya SAE: SJS Multy Blanding, SP-36, SJS Agrophos, Sawit Mas, dan Golden Premium.',path:'/produk/',active:'/produk/',body:`${hero('Portofolio Produk','Pelajari pilihan produk pupuk Sinar Jaya SAE. Informasi spesifikasi dan foto kemasan asli dapat dikonfirmasi kepada tim kami.','Produk')}<section><div class="container"><div class="product-grid">${productsCards}</div></div></section>`}));
for(const [slug,name,desc] of products){await mkdir(`public/produk/${slug}`,{recursive:true});await writeFile(`public/produk/${slug}/index.html`,page({title:`${name} | Produk Sinar Jaya SAE`,desc:`${name} — ${desc} Hubungi Sinar Jaya SAE untuk informasi produk.`,path:`/produk/${slug}/`,active:'/produk/',name,body:`${hero(name,desc,'Produk / '+name)}<section><div class="container intro-grid"><div class="product-image" style="min-height:360px"><span>Placeholder untuk foto kemasan asli ${name}</span></div><div class="prose"><p class="eyebrow">Produk Sinar Jaya SAE</p><h2>Informasi ${name}</h2><p>${desc}</p><p>Untuk informasi ketersediaan, spesifikasi, atau kebutuhan distribusi, silakan hubungi Sinar Jaya SAE melalui WhatsApp.</p><a class="button" href="${wa}" target="_blank" rel="noopener">Tanyakan Produk</a><p><a class="text-link" href="/produk/">← Kembali ke semua produk</a></p></div></div></section>`}));}
await writeFile('public/solusi/index.html',page({title:'Solusi Pertanian | Sinar Jaya SAE',desc:'Informasi solusi dan aplikasi pupuk pertanian dari Sinar Jaya SAE.',path:'/solusi/',active:'/solusi/',body:`${hero('Solusi untuk Kebutuhan Pertanian','Ruang informasi untuk mengenal produk dan mendiskusikan kebutuhan pupuk pertanian bersama tim Sinar Jaya SAE.','Solusi')}<section><div class="container cards"><article class="card"><h3>Fosfat alam</h3><p>Jelajahi portofolio produk pupuk fosfat alam Sinar Jaya SAE.</p></article><article class="card"><h3>Pertanian</h3><p>Komunikasikan kebutuhan produk pertanian Anda kepada tim kami.</p></article><article class="card"><h3>Sawit</h3><p>Pelajari produk Sawit Mas 13-6-27+TE dalam portofolio kami.</p></article></div></section>`}));
await writeFile('public/distribusi/index.html',page({title:'Distribusi Pupuk Indonesia | Sinar Jaya SAE',desc:'Sinar Jaya SAE melayani distribusi pupuk pertanian ke seluruh Indonesia dari Gresik, Jawa Timur.',path:'/distribusi/',active:'/distribusi/',body:`${hero('Distribusi untuk Seluruh Indonesia','Sinar Jaya SAE melayani kebutuhan distribusi pupuk pertanian di seluruh Indonesia dan pernah memiliki pengalaman ekspor ke Timor-Leste.','Distribusi')}<section><div class="container distribution-grid"><div class="panel"><h2>Jangkauan layanan</h2><p>Diskusikan kebutuhan produk dan tujuan pengiriman dengan tim kami agar layanan dapat disesuaikan dengan kebutuhan Anda.</p></div><div class="prose"><h2>Dari Gresik untuk kebutuhan nasional</h2><p>Kami berlokasi di Gresik, Jawa Timur, Indonesia. Untuk pertanyaan terkait produk maupun distribusi, gunakan kanal kontak resmi Sinar Jaya SAE.</p><a class="button" href="/kontak/">Hubungi Kami</a></div></div></section>`}));
await writeFile('public/artikel/index.html',page({title:'Artikel & Informasi | Sinar Jaya SAE',desc:'Pusat informasi Sinar Jaya SAE seputar pupuk fosfat alam, nutrisi tanaman, pupuk sawit, dan pemupukan.',path:'/artikel/',active:'/artikel/',body:`${hero('Artikel & Informasi','Ruang informasi yang disiapkan untuk pembahasan pupuk fosfat alam, nutrisi tanaman, pemupukan, dan produk Sinar Jaya SAE.','Artikel')}<section><div class="container article-grid">${['Pupuk fosfat alam','Fungsi fosfat bagi tanaman','Nutrisi tanaman','Pemupukan sawit','Mineral pertanian','Informasi produk'].map(x=>`<article class="article-card"><time>Segera hadir</time><h2>${x}</h2><p>Topik informasi ini sedang disiapkan dengan referensi yang dapat dipertanggungjawabkan.</p></article>`).join('')}</div></section>`}));
await writeFile('public/kontak/index.html',page({title:'Kontak | Sinar Jaya SAE',desc:'Hubungi Sinar Jaya SAE melalui WhatsApp, email, atau kunjungi informasi lokasi kami di Gresik, Jawa Timur.',path:'/kontak/',active:'/kontak/',body:`${hero('Hubungi Sinar Jaya SAE','Tim kami siap menerima pertanyaan terkait produk dan kebutuhan distribusi pupuk pertanian.','Kontak')}<section><div class="container contact-grid"><div><div class="contact-item"><strong>WhatsApp</strong><a href="${wa}" target="_blank" rel="noopener">0812-3999-8129</a></div><div class="contact-item"><strong>Email</strong><a href="mailto:cvsinarjayasae@gmail.com">cvsinarjayasae@gmail.com</a><br><a href="mailto:cinarjayasae@yahoo.com">cinarjayasae@yahoo.com</a></div><div class="contact-item"><strong>Jam operasional</strong>Senin–Sabtu, 08.00–16.00 WIB</div><div class="contact-item"><strong>Lokasi</strong>Gresik, Jawa Timur, Indonesia</div></div><div class="panel"><h2>Mulai percakapan</h2><p>Silakan sampaikan kebutuhan produk atau pertanyaan Anda melalui WhatsApp pada jam operasional.</p><a class="button" href="${wa}" target="_blank" rel="noopener">WhatsApp Sinar Jaya SAE</a></div></div></section>`}));

const paths=['/','/tentang-kami/','/produk/','/produk/sjs-multy-blanding/','/produk/sp-36/','/produk/sjs-agrophos/','/produk/sawit-mas-13-6-27-te/','/produk/golden-premium/','/solusi/','/distribusi/','/artikel/','/kontak/'];
const sitemapUrls=siteUrl ? paths.map((path)=>`  <url><loc>${absoluteUrl(path)}</loc></url>`).join('\n') : '  <!-- Add SITE_URL or siteUrl in site.config.json before publishing the production sitemap. -->';
await writeFile('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls}\n</urlset>\n`);
await writeFile('public/robots.txt', `User-agent: *\nAllow: /\n${siteUrl ? `\nSitemap: ${absoluteUrl('/sitemap.xml')}\n` : '\n# Set SITE_URL or siteUrl in site.config.json to publish the production sitemap URL.\n'}`);
